# Generated by Django 5.0.3 on 2024-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=15)),
                ('psw', models.CharField(max_length=10)),
                ('cpsw', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('lang', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('phn', models.IntegerField(verbose_name='default')),
            ],
        ),
    ]
