# Generated by Django 5.0.3 on 2024-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=15)),
                ('ConfirmPassword', models.CharField(max_length=15)),
                ('Dept_Id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
