# Generated by Django 5.0.3 on 2024-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('company', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
