# Generated by Django 5.0.3 on 2024-05-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='languages_known',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
