# Generated by Django 5.0.3 on 2024-05-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
