# Generated by Django 5.0.3 on 2024-04-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_details_cid_alter_details_cpsw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='cpsw',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='phn',
            field=models.IntegerField(verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='details',
            name='psw',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='details',
            name='qual',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='state',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='details',
            name='uname',
            field=models.CharField(max_length=15),
        ),
    ]
